// Collect every L("key", "English") in the sources into lang/template.txt, which is what
// a translator starts from.
//
// Deliberately a regex over the source rather than anything cleverer. The call shape is
// fixed by the macro in src/Loc.h and a real parse would buy nothing — but a regex CAN
// silently match less than it should, so this fails loudly on a suspiciously small
// harvest and check.mjs asserts the template is current.
//
//     node tools/extract-strings.mjs

import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

function sources(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) sources(p, out);
    else if (/\.(cpp|h)$/.test(name)) out.push(p);
  }
  return out;
}

// L("key", "text") and LF("key", "text with {}", value) — the text may contain escapes
// and adjacent "a" "b" concatenation, which is how a long panel body is written in C++.
// The trailing [,)] is what admits LF: its English text is followed by the arguments
// rather than by the closing bracket.
//
// The first version of this matched `\bL\(` only and silently skipped every LF call. The
// template came out short, and the check that compares template to source compared a
// stale template against the same stale collector and passed. Hence COUNT below.
const CALL = /\bLF?\(\s*"([^"]+)"\s*,\s*((?:"(?:[^"\\]|\\.)*"\s*)+)[,)]/g;

// Every call site, however malformed, just to count them. If this and CALL disagree the
// regex above has stopped matching something it should — which is a silent failure, so
// it is made loud.
const COUNT = /\bLF?\(\s*"/g;

export function collect() {
  const found = new Map();
  const dupes = [];
  let callSites = 0;
  for (const file of sources(join(ROOT, "src"))) {
    // Comments first: Loc.h documents the macro by showing a call, and without this the
    // example ends up in the template as a string every translator has to wonder about.
    const code = readFileSync(file, "utf8")
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/^[ \t]*\/\/.*$/gm, "");
    for (const m of code.matchAll(CALL)) {
      const key = m[1];
      // Join the adjacent literals, keeping their escapes as written: the language file
      // uses the same \n and \\ escapes, so this round-trips.
      const text = [...m[2].matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((x) => x[1]).join("");
      if (found.has(key) && found.get(key).text !== text) {
        dupes.push(key);
      }
      found.set(key, { text, file: relative(ROOT, file).replace(/\\/g, "/") });
    }
    callSites += (code.match(COUNT) || []).length;
  }
  return { found, dupes, callSites };
}

export function template(found) {
  const byFile = new Map();
  for (const [key, v] of found) {
    if (!byFile.has(v.file)) byFile.set(v.file, []);
    byFile.get(v.file).push([key, v.text]);
  }
  let out =
    "; Isekai Hero - translation template\n" +
    ";\n" +
    "; Copy this to <code>.txt (de.txt, zh.txt, pl.txt ...), put it in\n" +
    "; Data\\SKSE\\Plugins\\IsekaiHero\\lang\\, and set Language in IsekaiHero.ini.\n" +
    ";\n" +
    "; Translate the RIGHT side of each = only. Rules:\n" +
    ";   - \\n is a line break. Keep them: panel layouts are measured, not wrapped.\n" +
    ";   - {} is a value the mod fills in. Keep every one, in any order you need.\n" +
    ";   - Lines starting with ; are comments. UTF-8, no BOM needed.\n" +
    ";   - A key you delete or leave empty simply stays English. A partial\n" +
    ";     translation is a working translation.\n" +
    ";\n" +
    "; GENERATED by tools/extract-strings.mjs - re-run it after the mod updates to see\n" +
    "; which keys are new.\n";
  for (const [file, entries] of [...byFile].sort()) {
    out += `\n; --- ${file} ---\n`;
    for (const [key, text] of entries.sort()) {
      out += `${key} = ${text}\n`;
    }
  }
  return out;
}

if (process.argv[1] && process.argv[1].endsWith("extract-strings.mjs")) {
  const { found, dupes } = collect();
  if (dupes.length) {
    console.error(`same key, different English text: ${dupes.join(", ")}`);
    process.exit(1);
  }
  mkdirSync(join(ROOT, "lang"), { recursive: true });
  writeFileSync(join(ROOT, "lang", "template.txt"), template(found));
  console.log(`wrote lang/template.txt with ${found.size} strings`);
}
