// Generate fomod/ModuleConfig.xml from the preset list in make-presets.mjs, and the
// preset inis with it. One source of truth: adding a preset there adds it to the
// installer here, so the two can never disagree about which presets exist.
//
// Run `node tools/make-fomod.mjs` after touching IsekaiHero.ini or the preset list.

import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PRESETS, STARTS, HUDS, build } from "./make-presets.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// A screenshot for a step, IF the file is actually there. Emitting the attribute for a
// missing file gives the player an empty pane and no clue why, so an absent picture is
// simply no picture — drop a PNG into fomod/images and re-run to add one. Named here
// rather than at each call site so the whole set is visible in one place.
const missing = [];
const imagePath = (name) => {
  if (existsSync(join(root, "fomod", "images", name))) {
    return `fomod\\images\\${name}`;
  }
  missing.push(name);
  return "";
};
const image = (name) => {
  const p = imagePath(name);
  return p ? `<image path="${p}"/>` : "";
};

// The standard preset is the ini the archive already ships at its normal place, so a
// manual (non-manager) install of the same archive lands on exactly that file.
const sourceOf = (p) =>
  p.dir === "standard"
    ? "SKSE\\Plugins\\IsekaiHero.ini"
    : `fomod-presets\\${p.dir}\\IsekaiHero.ini`;

// One step per question. The options themselves install NOTHING — they only raise a flag.
// The ini is chosen afterwards from the pair of flags (conditionalFileInstalls below),
// which is the only way a FOMOD can offer two independent questions when the thing being
// installed is one whole file.
const step = (name, group, flag, options) => `
    <installStep name="${esc(name)}">
      <optionalFileGroups order="Explicit">
        <group name="${esc(group)}" type="SelectExactlyOne">
          <plugins order="Explicit">${options.map((o, i) => `
            <plugin name="${esc(o.name)}">
              <description>${esc(o.blurb)}</description>
              ${o.image ? image(o.image) : ""}
              <files/>
              <conditionFlags>
                <flag name="${flag}">${esc(o.key || "default")}</flag>
              </conditionFlags>
              <typeDescriptor><type name="${i === 0 ? "Recommended" : "Optional"}"/></typeDescriptor>
            </plugin>`).join("")}
          </plugins>
        </group>
      </optionalFileGroups>
    </installStep>`;

const conditionalInis = PRESETS.map((p) => `
      <pattern>
        <dependencies operator="And">
          <flagDependency flag="start" value="${p.start}"/>
          <flagDependency flag="hud" value="${p.hud || "default"}"/>
        </dependencies>
        <files>
          <file source="${sourceOf(p)}" destination="SKSE\\Plugins\\IsekaiHero.ini"
                priority="1"/>
        </files>
      </pattern>`).join("");

const xml = `<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://qconsulting.ca/fo3/ModConfig5.0.xsd">
  <moduleName>Isekai Hero</moduleName>
  <!-- The banner across the installer. The threat readings are the one thing that is
       visible without opening a menu, so they are what the mod looks like in play. -->
  <moduleImage path="${imagePath("threat-labels.png")}"/>

  <!-- GENERATED by tools/make-fomod.mjs - do not edit by hand. -->

  <!-- Everything that is not a setting. The ini is the only file this installer has an
       opinion about; it is chosen below. -->
  <requiredInstallFiles>
    <file   source="IsekaiHero.esp"                    destination="IsekaiHero.esp"/>
    <file   source="LICENSE"                           destination="LICENSE"/>
    <file   source="SKSE\\Plugins\\IsekaiHeroSKSE.dll"   destination="SKSE\\Plugins\\IsekaiHeroSKSE.dll"/>
    <folder source="SKSE\\Plugins\\IsekaiHero"           destination="SKSE\\Plugins\\IsekaiHero"/>
    <folder source="Sound"                             destination="Sound"/>
    <folder source="meshes"                            destination="meshes"/>
    <folder source="textures"                          destination="textures"/>
  </requiredInstallFiles>

  <installSteps order="Explicit">
    <installStep name="Interface">
      <optionalFileGroups order="Explicit">
        <group name="How the System draws itself" type="SelectExactlyOne">
          <plugins order="Explicit">
            <plugin name="Built-in">
              <description>The interface the mod draws itself. Needs nothing else, works everywhere the mod does.</description>
              ${image("builtin.png")}
              <files/>
              <typeDescriptor><type name="Recommended"/></typeDescriptor>
            </plugin>
            <plugin name="PrismaUI">
              <description>Renders the whole interface as a web page instead: the same screens, laid out with HTML and CSS. REQUIRES the PrismaUI framework to be installed separately - without it the mod silently falls back to the built-in interface, so this is safe to pick either way. This is the same patch that used to be a separate download.</description>
              ${image("prismaui.png")}
              <files>
                <!-- The icons are the same files the built-in path installs. Installed
                     twice from one source rather than shipped twice: the icon set is
                     almost the entire size of both archives. -->
                <file   source="PrismaUI\\views\\IsekaiHero\\index.html"
                        destination="PrismaUI\\views\\IsekaiHero\\index.html"/>
                <folder source="SKSE\\Plugins\\IsekaiHero\\icons"
                        destination="PrismaUI\\views\\IsekaiHero\\icons"/>
              </files>
              <typeDescriptor><type name="Optional"/></typeDescriptor>
            </plugin>
          </plugins>
        </group>

        <!-- Additive, not an alternative, so its own group: the MCM sits beside whichever
             interface was picked above rather than replacing it. SelectAny with a single
             entry is how FOMOD spells "a checkbox". -->
        <group name="Extras" type="SelectAny">
          <plugins order="Explicit">
            <plugin name="Mod Configuration Menu">
              <description>Adds an MCM under the usual Mod Configuration list, with every setting from IsekaiHero.ini and its explanation. REQUIRES SkyUI and MCM Helper. Leave it unticked if you do not have those - the mod is fully configurable through the ini either way, and this is the only thing in it that needs them.</description>
              <files>
                <folder source="MCM\\Config\\IsekaiHero"
                        destination="MCM\\Config\\IsekaiHero"/>
              </files>
              <typeDescriptor><type name="Optional"/></typeDescriptor>
            </plugin>
          </plugins>
        </group>
      </optionalFileGroups>
    </installStep>

${step("Start", "When the System wakes up", "start", STARTS)}
${step("Threat readings", "Readings over enemies", "hud", HUDS)}
  </installSteps>

  <!-- The two answers above pick one of the generated inis. Every combination is listed,
       so there is no path through the installer that leaves the settings file out. -->
  <conditionalFileInstalls>
    <patterns>${conditionalInis}
    </patterns>
  </conditionalFileInstalls>
</config>
`;

build();
mkdirSync(join(root, "fomod"), { recursive: true });
writeFileSync(join(root, "fomod", "ModuleConfig.xml"), xml);
console.log(`wrote fomod/ModuleConfig.xml with ${PRESETS.length} presets`);
if (missing.length) {
  // Not an error: the installer is complete without pictures, and half a picture set is
  // better than none. Said out loud, though, because a screenshot silently absent from
  // an installer is exactly the kind of thing nobody notices until a player asks.
  console.log(`  no picture yet for: ${[...new Set(missing)].join(", ")} ` +
              `(drop a PNG into fomod/images and run this again)`);
}
