// Generate fomod/ModuleConfig.xml from the preset list in make-presets.mjs, and the
// preset inis with it. One source of truth: adding a preset there adds it to the
// installer here, so the two can never disagree about which presets exist.
//
// Run `node tools/make-fomod.mjs` after touching IsekaiHero.ini or the preset list.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { PRESETS, build } from "./make-presets.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const esc = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// The standard preset is the ini the archive already ships at its normal place, so a
// manual (non-manager) install of the same archive lands on exactly that file.
const sourceOf = (p) =>
  p.dir === "standard"
    ? "SKSE\\Plugins\\IsekaiHero.ini"
    : `fomod-presets\\${p.dir}\\IsekaiHero.ini`;

const plugins = PRESETS.map(
  (p, i) => `
          <plugin name="${esc(p.name)}">
            <description>${esc(p.blurb)}</description>
            <files>
              <file source="${sourceOf(p)}" destination="SKSE\\Plugins\\IsekaiHero.ini"
                    priority="1"/>
            </files>
            <typeDescriptor>
              <type name="${i === 0 ? "Recommended" : "Optional"}"/>
            </typeDescriptor>
          </plugin>`).join("");

const xml = `<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://qconsulting.ca/fo3/ModConfig5.0.xsd">
  <moduleName>Isekai Hero</moduleName>

  <!-- GENERATED by tools/make-fomod.mjs - do not edit by hand. -->

  <!-- Everything that is not a setting. The ini is the only file this installer has an
       opinion about; it is chosen below. -->
  <requiredInstallFiles>
    <file   source="IsekaiHero.esp"                    destination="IsekaiHero.esp"/>
    <file   source="SKSE\\Plugins\\IsekaiHeroSKSE.dll"   destination="SKSE\\Plugins\\IsekaiHeroSKSE.dll"/>
    <folder source="SKSE\\Plugins\\IsekaiHero"           destination="SKSE\\Plugins\\IsekaiHero"/>
    <folder source="Sound"                             destination="Sound"/>
  </requiredInstallFiles>

  <installSteps order="Explicit">
    <installStep name="Interface">
      <optionalFileGroups order="Explicit">
        <group name="How the System draws itself" type="SelectExactlyOne">
          <plugins order="Explicit">
            <plugin name="Built-in">
              <description>The interface the mod draws itself. Needs nothing else, works everywhere the mod does.</description>
              <files/>
              <typeDescriptor><type name="Recommended"/></typeDescriptor>
            </plugin>
            <plugin name="PrismaUI">
              <description>Renders the whole interface as a web page instead: the same screens, laid out with HTML and CSS. REQUIRES the PrismaUI framework to be installed separately - without it the mod silently falls back to the built-in interface, so this is safe to pick either way. This is the same patch that used to be a separate download.</description>
              <files>
                <!-- The icons are the same files the built-in path installs. Installed
                     twice from one source rather than shipped twice: the icon set is
                     almost the entire size of both archives. -->
                <file   source="PrismaUI\\views\\IsekaiHero\\index.html"
                        destination="PrismaUI\\views\\IsekaiHero\\index.html"/>
                <folder source="SKSE\\Plugins\\IsekaiHero\\icons"
                        destination="PrismaUI\\views\\IsekaiHero\\icons"/>
              </files>
              <typeDescriptor><type name="Optional"/></typeDescriptor>
            </plugin>
          </plugins>
        </group>
      </optionalFileGroups>
    </installStep>

    <installStep name="Settings">
      <optionalFileGroups order="Explicit">
        <group name="Starting settings" type="SelectExactlyOne">
          <plugins order="Explicit">${plugins}
          </plugins>
        </group>
      </optionalFileGroups>
    </installStep>
  </installSteps>
</config>
`;

build();
mkdirSync(join(root, "fomod"), { recursive: true });
writeFileSync(join(root, "fomod", "ModuleConfig.xml"), xml);
console.log(`wrote fomod/ModuleConfig.xml with ${PRESETS.length} presets`);
